### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mr-propre-debug** [Vexcited/Takuzu#1]
Bonjour/bonsoir,
je viens de voir votre projet de trophées NSI et je voulais savoir si vous vous étiez grandement inspiré du jeu mobile [Subbiku](https://play.google.com/store/apps/details?id=com.pierrox.android.subiku&hl=fr&gl=US) car j'y suis moi-même un grand joueur !

Bonne journée/soirée !

**Comment by Vexcited** [comment]
Ça à l'air de ressembler, pour implémenter notre jeu on s'est tout simplement servi de la page Wikipédia ici présente : https://fr.wikipedia.org/wiki/Takuzu
